# Generated by Django 3.2.8 on 2021-10-29 11:51

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=400)),
                ('phone_number', models.CharField(max_length=10)),
                ('public_email', models.EmailField(max_length=254)),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.neighbourhood')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
