# Generated by Django 3.2.8 on 2021-10-30 18:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_business_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
