# Generated by Django 3.2.8 on 2021-10-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_business_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='health_contact',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_contact',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
